# Generated by Django 5.0.3 on 2024-04-01 03:25

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestOwner",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(blank=True, max_length=125)),
                ("first_name", models.CharField(blank=True, max_length=125)),
                ("last_name", models.CharField(blank=True, max_length=125)),
                ("phone", models.CharField(blank=True, max_length=125)),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=225, null=True),
                ),
                (
                    "prefecture",
                    models.CharField(blank=True, default="", max_length=225, null=True),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "address_detail",
                    models.CharField(blank=True, default="", max_length=225, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAITING_FOR_APPROVE", "Waiting For Approve"),
                            ("REJECT", "Reject"),
                            ("APPROVED", "Approved"),
                        ],
                        default="WAITING_FOR_APPROVE",
                        max_length=125,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=125)),
                ("last_name", models.CharField(blank=True, max_length=125)),
                ("phone", models.CharField(blank=True, max_length=125)),
                ("address", models.CharField(blank=True, max_length=225)),
                ("prefecture", models.CharField(blank=True, max_length=225)),
                ("address_detail", models.CharField(blank=True, max_length=225)),
                ("postcode", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_first_login", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_check_notification_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_change_password_at",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("APPROVED", "Approved"),
                        ],
                        default="INACTIVE",
                        max_length=125,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserVerifyCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=8)),
                ("expire_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_verify_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_verify_code",
            },
        ),
    ]
